version: '3.9'

services:
  api:
    build: .
    image: api-springboot:latest
    environment:
      - DB_URL=jdbc:jdbc:postgresql://quackdb.postgres.database.azure.com:5432/postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - EMAIL_KEY=${EMAIL_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    env_file:
      - ./env
    ports:
      - "8888:8888"
