spring.datasource.url=jdbc:postgresql://quackdb.postgres.database.azure.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=987654321Qa@
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=primo-pato-o-pato-do-seu-primo-muito-amado
jwt.expiration=86400000

# Configuração do servidor SSL
server.port=8443

server.ssl.key-store=/app/keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-alias=tomcat
server.ssl.key-password=changeit
server.ssl.key-store-type=PKCS12