server.port=8888
spring.datasource.url=jdbc:postgresql://quackdb.postgres.database.azure.com:5432/postgres
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=primo-pato-o-pato-do-seu-primo-muito-amado
jwt.expiration=86400000

sendgrid.api.key=${EMAIL_KEY}
spring.mail.from=${EMAIL_FROM}
